### PR TITLE
Fixed bug causing flickering between article categories

### PR DESCRIPTION
**Pull request by DrewStephensCoding**
When switching between categories, slight flicker happens.

### CODE REVIEW

**Comment by Spikeysanju** [comment]
@DrewStephensCoding  Pls run the following commands inside android studio terminal

1. `./gradlew ktLintCheck`
2. `./gradlew ktLintFormat`

**Review by Spikeysanju — APPROVED** [review]
LGTM!

**Comment by Spikeysanju** [comment]
PR Merged!... Thanks for you contribution 🥳🙌

**Comment by DrewStephensCoding** [comment]
> @DrewStephensCoding  PR Merged!... Thanks for you contribution 🥳🙌

My first one! Thank you for giving me the opportunity!

**Comment by Spikeysanju** [comment]
> > @DrewStephensCoding  PR Merged!... Thanks for you contribution 🥳🙌
> 
> My first one! Thank you for giving me the opportunity!

Congrats buddy!... Looking forward for more contribution ♥️

**Pull request merged**
