### PR TITLE
Add Share Article feature

### PR DESCRIPTION
**Pull request by Spikeysanju**

### CODE REVIEW

**Comment by Spikeysanju** [comment]
@ELTEGANI PR Merged 🚀. Thanks for your contribution 👍

**Comment by ELTEGANI** [comment]
> @ELTEGANI PR Merged. Thanks for your contribution

You Wellcome :+1:

**Comment by Spikeysanju** [comment]
@ELTEGANI  I think you haven't taken icon from tabler icons. Anyway I have updated it.

**Comment by ELTEGANI** [comment]
> @ELTEGANI  I think you haven't taken icon from tabler icons. Anyway I have updated it.

@Spikeysanju thought you will let me re push it.The project is awesome I will keep contribute to it.

**Comment by Spikeysanju** [comment]
I trusted your words that you have taken icons from table icons, it's my mistake I reviewed only the code. Anyway, don't lie hereafter. Thanks 🙂👍.

**Comment by ELTEGANI** [comment]
> I trusted your words that you have taken icons from table icons, it's my mistake I reviewed only the code. Anyway, don't lie hereafter. Thanks 🙂👍.

Sir sorry for that i didnt mean lie to you also its my mistake not edit the title to let you know.😊👍👍

**Pull request merged**
