### PR TITLE
Add Swipe refresh

### PR DESCRIPTION
**Pull request by ch8n**
hi @Spikeysanju 
I have refactored some code as was added swipe to refresh, please do the code review

thanks,
Regards
Chetan Gupta

### CODE REVIEW

**Comment by ch8n** [comment]
@Spikeysanju please also tag this PR as with Hacktober fest accepted before merge

**Comment by Spikeysanju** [comment]
> hi @Spikeysanju 
> I have refactored some code as was added swipe to refresh, please do the code review
> 
> thanks,
> Regards
> Chetan Gupta

Reviewing your PR 👍. Will let you know when it's done.

**Review by Spikeysanju — APPROVED** [review]
Looks good!... PR Approved

**Comment by Spikeysanju** [comment]
Hey buddy @ch8n you have done a great job. This is what the expected behaviour. Everything LGTM 👏. Merging PR 🚀

**Comment by Spikeysanju** [comment]
@ch8n PR Merged 🚀. Thanks for your contribution mate 👍.

**Comment by ch8n** [comment]
> @ch8n PR Merged 🚀. Thanks for your contribution mate 👍.

It was fun, do let me we can collab on other projects as well

**Comment by Spikeysanju** [comment]
For sure buddy. I'm working on `Multi module project in Jetpack Compose` rn. Soon will let you know mate 🙌

**Pull request merged**
