### PR TITLE
Network connectivity

### PR DESCRIPTION
**Pull request by ch8n**
Hi @Spikeysanju,
I have added network observing capabilities as per the requirements. please do the code review.
Looking forward to your feedback.

Thanks!

Regards,
Chetan

### CODE REVIEW

**Comment by Spikeysanju** [comment]
@ch8n Hey thanks for taking time to contribute. Your implementation was good. But there are few issues there.

1. App Crashes when opening in `offline mode `.
2. When I turn off the internet, No internet connection is showing fine. But` when I switch from dark/light theme while in offline mode the app got crashed`
3. When` I'm coming back from Bookmarks fragment -> Articles Fragment app crashes when in offline mode`

We have to `check whether there is an internet connection before fetching the post from the NY times
`
Kindly let me know what's your thought on this, Thanks.

**Comment by ch8n** [comment]
@Spikeysanju this crash has been happening earlier as well, I have raised an Issue already regarding this behavior. This bug is independent of the functionality I have implemented. 

This is separate functionality and will require refresh handling and pull refresh gesture as well. Please create a new PR as well

**Comment by ch8n** [comment]
> @Spikeysanju this crash has been happening earlier as well, I have raised an Issue already regarding this behavior. This bug is independent of the functionality I have implemented.
> 
> This is separate functionality and will require refresh handling and pull refresh gesture as well. Please create a new PR as well

**Comment by Spikeysanju** [comment]
Hey buddy @ch8n  Everything LGTM 👍. We have to add Refresh handling & Swipe to refresh for this app for better user experience. I will assign you those above issue which was already created by you. Thanks a ton for your contribution. Merging PR 🚀

**Comment by ch8n** [comment]
hi @Spikeysanju Hacktober fest guideline has been updated please mark this with appropriate tag 
https://github.com/digitalocean/hacktoberfest/pull/596

**Pull request merged**
